### ISSUE TITLE
Update the documents to use the new Relaton XML format

### ISSUE THREAD

**Issue by andrew2net** [CalConnect/published-csd#1]
The documents generated from the older format, and the new metanorma can’t render them properly (bibdata schema was changed). So we need to update all the documents to use the newer metanorma and upload the newly generated XML into the “csd/“ submodule.

**Comment by andrew2net** [comment]
@ronaldtse as I see we need to do next updates:
- a `docidentifier`'s type should be changed form `csd` to `CC`
- an `editorialgroup` should be wrapped by an `ext` element

Did I miss something?

**Comment by ronaldtse** [comment]
@andrew2net yes, but we can achieve this by regenerating all the documents with the new MN version anyway.
